[all]
apm-test-master01  ansible_host=10.134.16.63  ip=10.134.16.63  etcd_member_name=etcd1
apm-test-master02  ansible_host=10.134.16.64  ip=10.134.16.64  etcd_member_name=etcd2
apm-test-master03  ansible_host=10.134.16.65  ip=10.134.16.65  etcd_member_name=etcd3
apm-test-worker01  ansible_host=10.134.16.66  ip=10.134.16.66
apm-test-worker02  ansible_host=10.134.16.67  ip=10.134.16.67
apm-test-worker03  ansible_host=10.134.16.68  ip=10.134.16.68

[kube_control_plane]
apm-test-master01
apm-test-master02
apm-test-master03

[etcd]
apm-test-master01
apm-test-master02
apm-test-master03

[kube_node]
apm-test-worker01
apm-test-worker02
apm-test-worker03

[k8s_cluster:children]
kube_control_plane
kube_node

[calico_rr]

# AWX inventory grup mappingleri
[masters]
apm-test-master01
apm-test-master02
apm-test-master03

[workers]
apm-test-worker01
apm-test-worker02
apm-test-worker03
